FROM node:20-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

COPY apps/web/public ./public
COPY apps/web/.next/standalone ./
COPY apps/web/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
